knsjerome/cmpt-354-project

- README.md
- server/sql/init_db.sql
Created an initialization script for the PostgreSQL DB.
> Implement DB Schema

- server/handlers.go
- server/main.go
- server/models/models.go
- server/models/postgresql/players.go
- server/sql/init_db.sql
As per the conversation between @ksmolko  and myself, the email attribute seems to be redundant given the use of the username attribute.
> Remove email attribute from the player relation

- client/package-lock.json
- client/package.json
- client/src/components/login/LoginForm.vue
- client/src/components/registration/RegistrationForm.vue
- client/src/main.js
- client/src/router/index.js
- client/src/views/Registration.vue
Add form that allows users to register.
Add link from login back to registration page and vice versa.
Add `vuelidate` dependency - used for form validation.
**See Discord chat for registration images.**
> Add registration capabilitites

- README.md
- server/config.go
- server/main.go
- server/sample_config.yml
- server/sql/init_db.sql
- server/sql/populate_db.sql
- server/tests.go
Includes some go code that will automatically populate the DB if `test_run` is set to `true` in `config.yml`
Also includes some general changes to the DB schema:
* Create `id` key for characters and campaigns
* Add maximum bounds to most numeric types
* Made most attributes not nullable
* Remove some redundancy from subclass names
All changes to the schema have been reflected in the written schema and ER diagram.
> Populate DB with preset values for testing

- server/sql/init_db.sql
- server/sql/populate_db.sql
Changes have been reflected in db schema and ER diagram.
> Add dungeon_master attribute to Campaign

- README.md
Add further instructions for installing required software.
Fix some markdown linting errors present in the file.
> Update root-level README.md

- server/handlers.go
- server/main.go
- server/models/postgresql/characters.go
Since this project is fairly self-contained, there is no explicity need
for the flexible interfaces currently used. As such, the interfaces now
use the data types from `models` package for improved readability and
usability.
> Update application interfaces for clarity

- server/handlers.go
- server/main.go
- server/models/models.go
- server/models/postgresql/spells.go
- server/routes.go
Add 3 new spell-related APIS:
- Create a spell
- Retrieve an individual spell
- Retrieve all spells belonging to a character
Add handlers for each API.
Add new SpellModel type.
Add spells interface to application.
> Add APIS for spell insertion and retrieval

- client/src/components/dashboard/InfoPane.vue
- client/src/components/dashboard/Spells.vue
- client/src/components/login/LoginForm.vue
- client/src/components/registration/RegistrationForm.vue
- client/src/layouts/NavDrawer.vue
- client/src/main.js
- client/src/plugins/vuetify.js
See the Discord chat for update images.
> Update web theme and add spell display to the GUI

- client/src/components/account/ProfileCard.vue
- client/src/layouts/NavDrawer.vue
- client/src/router/index.js
- client/src/store/modules/authentication.js
Major changes:
- Add the ability to logout from the frontend. Since we don't track user sessions in the backend, no backend changes are required.
> Implement logout capabilities in the frontend

- client/src/components/dashboard/InfoPane.vue
- client/src/components/dashboard/Items.vue
Add code to fetch character items in a similar fashion to what has been
done with character spells.
> Populate item tab on the dashboard GUI

- client/src/components/login/StatsBanner.vue
- client/src/views/Login.vue
Added a banner component which displays some stats from the application.
This banner pulls data from the SQL triggers that tick when a new
player, character, etc is created.
> Add stats banner to login page

- .gitignore
- server/handlers.go
- server/main.go
- server/models/models.go
- server/models/postgresql/belongs_to.go
- server/models/postgresql/campaigns.go
- server/routes.go
Created entity models and functions for "Campaign" and "BelongsTo" relations. This is part of the work needed for #45.
> Backend for "New Campaign" page

- client/src/components/characters/Background.vue
- client/src/components/characters/Class.vue
- client/src/components/characters/CreationStepper.vue
- client/src/components/characters/Stats.vue
Overview:
- This pull request adds functional to the character creation process in the GUI.
- User-entered data is emitted and collected at each step of the process, then packaged together and sent in an HTTP request.
Other concerns/todos:
- Form validation is needed at each step. Right now it's possible to create a character with a blank name, for example.
- The backend server is not yet ready to handle the dynamic nature of class attributes, which change based on the class that the user has picked for their character. Creation still works, but the class data is currently unused at the moment.
> Make character creation GUI functional

- client/src/router/index.js
Overview: We are now at point in development where all GUI routes should be protected. It doesn't make sense to have an unauthenticated user because we can't gather any meaningful data.
> Protect all relevant GUI routes

- client/src/App.vue
- client/src/components/characters/creation/CreationStepper.vue
- client/src/components/characters/updating/CharacterInfo.vue
- client/src/store/index.js
- client/src/store/modules/notifications.js
Added a new component for the GUI which gives user feedback via notifications. An example can be seen below:
> Add global notification snackbar

- server/sql/init_db.sql
Add several CHECK statements to verify int and text fields are cannot be
negative or empty.
Add many NOT NULL constraints on fields that are not supposed to be
nullable.
> Add more database constraints to prevent erroneous data scenarios

- client/src/components/characters/updating/CharacterInfo.vue
I changed the order of the Original Stats just so they would line up with the modifiers. So I needed to move Speed over to the right.
> Adding in Character Stat Modifiers

- client/src/components/characters/updating/CharacterInfo.vue
- client/src/components/dashboard/InfoPane.vue
Implement better error handling when fetching character. The fetched
character array will now be checked for null values before it is
assigned.
Add error notifications when characters cannot be fetched.
> Fix silently failing character fetch logic

- client/src/components/characters/creation/Class.vue
- client/src/components/characters/creation/CreationStepper.vue
This PR corrects the attributes available during the character creation GUI process to match what is available in the backend (more or less).
> Update class attributes in creation process GUI

- server/handlers.go
- server/main.go
- server/models/models.go
- server/models/postgresql/items.go
- server/models/postgresql/spells.go
- server/routes.go
- server/sql/populate_db.sql
Created two endpoints,
`r.GET("/character/:id/item/weight"` for total weight of all items a character has
`r.GET("/character/:id/spell/count-per-school"`  for the count of spells belonging to each school
Also updated the population script to add the class attribute due to new change
> Add aggregation queries in the backend

- client/src/components/characters/creation/Background.vue
- client/src/components/characters/creation/Class.vue
- Added basic validation to check for required fields and their accepted values.
- Users will now be unable to create a character until all required fields are filled out.
> Validate user inputs during character creation

- client/src/components/dashboard/InfoPane.vue
- client/src/components/dashboard/Items.vue
- client/src/components/dashboard/Spells.vue
- server/handlers.go
- server/main.go
- server/models/models.go
- server/models/postgresql/items.go
- server/routes.go
Add a spell count table to the spells dashboard tab.
Add an item stat table to the items dashboard tab.
> Create GUI elements for aggregation queries

- client/src/components/dashboard/Campaigns.vue
- client/src/components/dashboard/InfoPane.vue
- server/handlers.go
- server/main.go
- server/models/postgresql/campaigns.go
- server/routes.go
> Add campaigns to dashboard

- client/src/components/campaign/modification/AddMilestoneForm.vue
- client/src/components/campaign/modification/CampaignModifier.vue
- client/src/components/campaign/modification/MilestoneTimeline.vue
- server/handlers.go
- server/main.go
- server/models/postgresql/milestones.go
- server/routes.go
> Add campaign milestones

- client/src/components/campaign/modification/CampaignModifier.vue
- server/handlers.go
- server/main.go
- server/models/models.go
- server/models/postgresql/campaigns.go
- server/routes.go
> Add campaign join query and corresponding GUI element

- client/src/components/campaign/modification/CampaignModifier.vue
Add new column to the campaign participants table that indicates if the
player in a row has had perfect attendance for all campaigns created by
the logged-in player.
> Add attendance table column for campaign management GUI

- client/src/components/characters/updating/CharacterInfo.vue
- server/handlers.go
- server/main.go
- server/models/postgresql/characters.go
- server/routes.go
Front-end & Back-end code for handling character update functionality.
> Changes for character update functionality
